module.exports = {
  sidebar: [
    {
      type: 'doc',
      id: 'Welcome',
      label: 'Welcome'
    },
    {
      type: 'category',
      label: 'Documentation',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'Documentation'
        }
      ]
    }
  ]
};
